openapi: 3.0.0
info:
  version: 1.0.0
  title: Site of Refuge Hosts API
  description: An API that allows people who wish to host refugees to interact with Site of Refuge
  termsOfService: https://siteofrefuge.com/tos
  contact:
    name: Developers
    url: https://siteofrefuge.com
    email: info@siteofrefuge.com
  license:
    name: Site of Refuge License
    url: https://siteofrefuge.com/license

servers: 
  - url: https://api-dev.siteofrefuge.com/v1
    description: Dev Server
    
  - url: https://api.siteofrefuge.com/v1
    description: Production Server
    
paths:
  /hosts:
    get:
      description: Get a summary list of hosts registered in the system
      
      parameters: 
        - name: region
          in: query
          description: The region where the host is located. This is in ISO 3166-2 format.
          schema:
            type: string
            minLength: 4
            maxLength: 6
            pattern: '^[A-Z]{2}-[A-Z0-9]{1,3}$'
            example: PL-26

      responses:
        200:
          description: Successfully queried host information
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HostSummary'
                  
    post:
      description: Registers a new host in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref:  '#/components/schemas/Host'
      responses:
        201:
          description: Created
  
  /hosts/{id}:
    get:
      description: Get information about a specific host
      parameters:
        - name: id
          description: Host id in UUID/GUID format
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Id'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Host'
        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: Host not found
                type: string
                example: Not found
              
components:
  schemas:
    Availability:
      properties:
        date_available:
          type: string
          format: date
          description: Date when shelter will be available
        active:
          type: boolean
          description: Is this shelter currently available for matching with refugees?
        length_of_stay:
          type: string
          description: How long a refugee can stay
          enum: 
            - A few days, up to a week
            - Up to a month
            - At least 2 to 4 months
            - Over 4 months

    Contact:
      description: Contact information of a host
      properties:
        name:
          type: string
          description: The host's full name
          minLength: 3
          maxLength: 256
        methods:
          description: The way(s) in which this host can be contacted
          type: array
          items:
            $ref: '#/components/schemas/ContactMethod'
      required:
        - name
        - methods

    ContactMethod:
      description: The method in which this host can be contacted
      properties:
        method:
          type: string
          description: The actual way to contact the host
          enum:
            - Phone
            - Email
            - SMS
        value:
          type: string
          description: The details on how to contact this host (actual phone number, email address etc)
        verified:
          type: boolean
          description: Has this contact method been verified?
          default: false
      required:
        - method
        - value

    Host:
      description: Detailed information about a host
      properties:
        summary:        
          $ref: '#/components/schemas/HostSummary'
        contact:
          $ref: '#/components/schemas/Contact'
      required:
        - summary
        - contact

    HostSummary:
      description: Summary of a Host
      properties:
        id: 
          $ref: '#/components/schemas/Id'
        region:
          type: string
          description: The region where the host is located. This is in ISO 3166-2 format.
          minLength: 4
          maxLength: 6
          pattern: '^[A-Z]{2}-[A-Z0-9]{1,3}$'
          example: PL-26
        allowed_people:
          type: integer
          format: int32
          example: 2
        restrictions:
          description: Any restrictions the host has for this shelter
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/Restrictions'
        shelter:
          type: string
          oneOf:
            - $ref: '#/components/schemas/Shelter'
        languages:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/SpokenLanguages'
        availability:
          $ref: '#/components/schemas/Availability'
      required:
        - id
        - region
        - allowed_people
        - shelter
        - availability
        
    Id:
      type: string
      description: Unique identifier in UUID/GUID format
      pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
      example: '3F2504E0-4F89-41D3-9A0C-0305E82C3301'
        
    Restrictions:
      type: string
      enum:
        - Pets
        - Kids
        - Adult men
        - Adult women
        
    Shelter:
      type: string
      enum:
        - House with several rooms
        - Independent apartment
        - Room in a house of an apartment where you live
        - A bed in a shared room
        - A space in a hotel/hostel

    SpokenLanguages:
      type: string
      enum:
        - English
        - Ukrainian
        - Polish
        - Russian
        - Other
